/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BubbleEffect: typeof import('./src/components/BubbleEffect.vue')['default']
    ConfettiEffect: typeof import('./src/components/effects/ConfettiEffect.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    LoadingIndicator: typeof import('./src/components/ui/LoadingIndicator.vue')['default']
    MobileMenuButton: typeof import('./src/components/common/MobileMenuButton.vue')['default']
    NameDisplay: typeof import('./src/components/NameDisplay.vue')['default']
    PageLoading: typeof import('./src/components/common/PageLoading.vue')['default']
    RollCall: typeof import('./src/components/sections/RollCall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SpeechSystem: typeof import('./src/components/SpeechSystem.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ui/ThemeSwitcher.vue')['default']
  }
}
